import type { VisualDefinition } from "@difracta/core";

export const ribbonField: VisualDefinition = {
  kind: "visual",
  id: "ribbon-field",
  name: "Ribbon Field",
  description:
    "Ribbons of light drift through the Surface, bending in turbulence and leaving trails. Every aspect is a Parameter, so this is the Visual to try when a Controller needs something to move.",
  backend: "canvas",
  parameters: {
    count: {
      kind: "number",
      label: "Count",
      description: "How many ribbons are in the air.",
      default: 24,
      min: 1,
      max: 200,
      step: 1,
    },
    length: {
      kind: "number",
      label: "Length",
      default: 40,
      min: 2,
      max: 200,
      step: 1,
      unit: "px",
    },
    width: {
      kind: "number",
      label: "Width",
      default: 3,
      min: 1,
      max: 30,
      step: 0.5,
      unit: "px",
    },
    speed: {
      kind: "number",
      label: "Speed",
      default: 1,
      min: 0,
      max: 5,
      step: 0.1,
      unit: "x",
    },
    turbulence: {
      kind: "number",
      label: "Turbulence",
      description: "How much the wind twists the ribbons.",
      default: 0.4,
      min: 0,
      max: 1,
      step: 0.01,
    },
    gravity: {
      kind: "number",
      label: "Gravity",
      default: 0,
      min: -1,
      max: 1,
      step: 0.01,
    },
    spread: {
      kind: "number",
      label: "Spread",
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
    },
    fade: {
      kind: "number",
      label: "Fade",
      description: "How fast a trail dies out behind its ribbon.",
      default: 0.2,
      min: 0.01,
      max: 1,
      step: 0.01,
    },
    hueDrift: {
      kind: "number",
      label: "Hue drift",
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: "°",
    },
    glow: {
      kind: "number",
      label: "Glow",
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
    },
    palette: {
      kind: "choice",
      label: "Palette",
      default: "aurora",
      options: [
        { value: "aurora", label: "Aurora" },
        { value: "ember", label: "Ember" },
        { value: "ice", label: "Ice" },
        { value: "mono", label: "Mono" },
      ],
    },
    trails: {
      kind: "boolean",
      label: "Trails",
      description: "Ribbons leave a fading trace behind them.",
      default: true,
    },
    mirror: {
      kind: "boolean",
      label: "Mirror",
      description: "The left half is mirrored onto the right.",
      default: false,
    },
    color: { kind: "color", label: "Color", default: [0.6, 0.9, 1, 1] },
    background: {
      kind: "color",
      label: "Background",
      description: "Transparent by default, so Layers below show through.",
      default: [0, 0, 0, 0],
    },
  },
  cues: [
    {
      key: "gust",
      label: "Gust",
      description: "A burst of wind through the field.",
    },
  ],
};
